### ISSUE TITLE
Error on directories that end with `*.html`

### ISSUE THREAD

**Issue by ehmicky** [martinbean/netlify-plugin-amp-server-side-rendering#1]
When the publish directory contains directories whose filename ends with `*.html`, the following [line of code](https://github.com/martinbean/netlify-plugin-amp-server-side-rendering/blob/46798f590c18626e0edb50f609a661e4c98ed293/src/index.js#L17) results in:

```
EISDIR: illegal operation on a directory, read
```

**Comment by martinbean** [comment]
@ehmicky Thanks! I’ll take a look at this and ensure the plugin only operates on files and dismisses directories.

**Comment by martinbean** [comment]
Fixed by #2.
