### ISSUE TITLE
Plugin "netlify-plugin-amp-server-side-rendering" internal error

### ISSUE THREAD

**Issue by aaron-purplerain** [martinbean/netlify-plugin-amp-server-side-rendering#9]
![image](https://user-images.githubusercontent.com/63337245/110570693-4f8fd780-8191-11eb-95e3-cef5bce47c54.png)

**Comment by martinbean** [comment]
@aaron-purplerain Thanks. Is this a public repo you tried the plugin with?

**Comment by martinbean** [comment]
Closing due to lack of information.
